# Generated by Django 4.2.30 on 2026-05-09 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='分类图标')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'categories',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('group_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='团购价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sold_count', models.IntegerField(default=0, verbose_name='已售数量')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('up', '上架'), ('down', '下架')], default='draft', max_length=10, verbose_name='状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='分类')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='团长')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['sort', '-created_at'],
            },
        ),
    ]
