version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: photo-album-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: photo-album

volumes:
  mongo-data:
