server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:data/express_station.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
