# Generated by Django 4.2.30 on 2026-05-09 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='团购标题')),
                ('group_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='团购价')),
                ('min_group_size', models.IntegerField(default=2, verbose_name='最小成团人数')),
                ('current_people', models.IntegerField(default=0, verbose_name='当前人数')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('active', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buys', to=settings.AUTH_USER_MODEL, verbose_name='团长')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buys', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '团购活动',
                'verbose_name_plural': '团购活动',
                'db_table': 'group_buys',
                'ordering': ['-created_at'],
            },
        ),
    ]
