version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cloud-notes-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: cloud_notes
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
