server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./booklist.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
