server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:data/leave_system.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin123
  
  jpa:
    database-platform: com.example.leavesystem.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
