spring:
  datasource:
    url: jdbc:sqlite:secondhand.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8080
  servlet:
    context-path: /api

upload:
  path: ./uploads
