# Generated by Django 4.2.30 on 2026-05-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='职位')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='擅长技能')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '离职')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技师',
                'verbose_name_plural': '技师管理',
                'db_table': 'technician',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('shift', models.CharField(choices=[('morning', '早班'), ('afternoon', '午班'), ('evening', '晚班'), ('full', '全天'), ('off', '休息')], default='full', max_length=20, verbose_name='班次')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='management.technician', verbose_name='技师')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班管理',
                'db_table': 'schedule',
                'ordering': ['-date', 'technician'],
                'unique_together': {('technician', 'date')},
            },
        ),
    ]
