import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import 'vant/lib/index.css'
import { Button, Form, Field, Popup, Picker, DatePicker, Cell, CellGroup, List, Tab, Tabs, Empty, Toast, Dialog, Loading, NavBar, Tabbar, TabbarItem, Area, Switch, Stepper, PasswordInput, NumberKeyboard, Image as VanImage, Icon, NoticeBar, Badge, PullRefresh, ActionSheet, DropdownMenu, DropdownItem, RadioGroup, Radio, Checkbox, CheckboxGroup, Grid, GridItem, Card, Tag, Divider, Progress, Circle, CountDown, Lazyload, Search } from 'vant'

const app = createApp(App)

app.use(router)
app.use(Button)
app.use(Form)
app.use(Field)
app.use(Popup)
app.use(Picker)
app.use(DatePicker)
app.use(Cell)
app.use(CellGroup)
app.use(List)
app.use(Tab)
app.use(Tabs)
app.use(Empty)
app.use(Toast)
app.use(Dialog)
app.use(Loading)
app.use(NavBar)
app.use(Tabbar)
app.use(TabbarItem)
app.use(Area)
app.use(Switch)
app.use(Stepper)
app.use(PasswordInput)
app.use(NumberKeyboard)
app.use(VanImage)
app.use(Icon)
app.use(NoticeBar)
app.use(Badge)
app.use(PullRefresh)
app.use(ActionSheet)
app.use(DropdownMenu)
app.use(DropdownItem)
app.use(RadioGroup)
app.use(Radio)
app.use(Checkbox)
app.use(CheckboxGroup)
app.use(Grid)
app.use(GridItem)
app.use(Card)
app.use(Tag)
app.use(Divider)
app.use(Progress)
app.use(Circle)
app.use(CountDown)
app.use(Lazyload)
app.use(Search)

app.mount('#app')
