# Generated by Django 4.2.30 on 2026-05-09 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='自提点名称')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('business_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='营业时间')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('status', models.CharField(choices=[('active', '营业中'), ('closed', '已关闭')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to=settings.AUTH_USER_MODEL, verbose_name='团长')),
            ],
            options={
                'verbose_name': '自提点',
                'verbose_name_plural': '自提点',
                'db_table': 'pickup_points',
                'ordering': ['-created_at'],
            },
        ),
    ]
