# Generated by Django 4.2.7 on 2026-05-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=50, unique=True, verbose_name='图书编号')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='出版社')),
                ('total_quantity', models.IntegerField(default=1, verbose_name='总数量')),
                ('available_quantity', models.IntegerField(default=1, verbose_name='可借数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True, verbose_name='借阅日期')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='归还日期')),
                ('is_returned', models.BooleanField(default=False, verbose_name='是否已归还')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'borrow_record',
            },
        ),
    ]
