server.port=8080

spring.datasource.url=jdbc:sqlite:milktea_pos.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
